### ISSUE TITLE
Navigating before the current route's activation has completed breaks rendering

### ISSUE THREAD

**Issue by bryanrsmith** [aurelia/router#110]
If you navigate to a new route before the previous VM's `activate` completes, both templates end up in the `<router-view>`.

navigation-skeleton repro:
1. Start on the welcome tab.
2. Click on the Flickr tab.
3. Before the flickr request has completed, click back to the Welcome tab (hit 'confirm' quickly).

 Result: When the flickr request comes back its results are rendered, and the flickr template is appended to the `<router-view>`. The welcome template is also appended to the `<router-view>` below the flickr section.

**Comment by jadrake75** [comment]
ha..... I was just hitting this and was baffled as to what was going on.

Also if you need to redirect a route in activate (for example, detect a "last visited object and set that on the route path" you have to call the navigateToRoute( ) in a timeout after activate completes or it will remove the current route path.

ie.  if the current view-model is mapped to

/details

and has a sub-route that is dynamic such as :name then if you attempt to call navigateToRoute inside Activate instead of getting a full route path of

/#/details/some_name

You get

#/some_name

Placing it in a timeout works, but ideally there should be away to redirect before or during activation.

**Comment by bryanrsmith** [comment]
Closing, as this appears to be an issue with the animator tracked in aurelia/framework#132.
