### ISSUE TITLE
Child routers are causing a parent router dom refresh

### ISSUE THREAD

**Issue by jadrake75** [aurelia/router#114]
First off this situation happens both for transient and singleton view-models....  The only observed difference I saw was the construction was called once vs. each time.

If you have a simple page configuration where there is a page (call it parent) that contains child routes included via the <router-view> tag the parent DOM is completely unloaded and loaded from the DOM with each child route change.

Lets take a simple example of master-detail views.  You have a list of objects (lets call it "/list").  When you pick an object you want to child route to "/list/:itemId" where the itemId is the parameter of the selected item in the list.  I was creating a subscription on a channel in the parent view-model in the constructor and was aghast to see as I clicked through items, it was effectively adding another subscriber callback to the list.  Changing it to a @singleton() and then moving the code to the attach() function still got called each time.   ie. if I clicked 5 times I had 5 subscribers!  It was at this point I discovered what was happening... the parent view-model was getting 
- deactivated
- activated
- detached
- attached

But nothing was changing in the parent view-model that should cause the detach/attached calls.  If I removed the @singleton() on the view-model I was also seeing the parent view-model be instantiated each time.  

This would be a significant performance hit for more applications that follow this logical model.  Especially if the parent view-model is complicated (expensive query or DOM construction like a 1000+ row table).    Again I believe this only applies to cases that have a router-view managing the child-routers.    Ideally in this case the detached() and attached() functions should not be called on the parent route if it is a router-view replacement.

To do the navigation, I am calling

this.router.navigate("childRoute");

If there is a different call I should be making to avoid this unloading of the DOM then I am sorry for the confusion.  It may be possible if it is agreed this is an issue (and for my corporate application I am starting development on it will be) perhaps a new method like "navigateChild" or something could be used to simply process the router-view handling.

**Comment by zhhz** [comment]
+1
it would be nice if we can treat the child routes differently other than the normal life cycle calls...

**Comment by EisenbergEffect** [comment]
@jadrake75 The router was designed specifically to not do what you are describing. Either we've had a regression or there's something seriously wrong in some other way.  But, I've never seen this behavior and as I said it was designed not to do that. Can you reproduce it in a plunkr? @bryanrsmith Can you help investigate this?

**Comment by jadrake75** [comment]
Sure, I will work to add a plunker for it..... Glad to hear it is NOT
supposed to work that way!

**Comment by bryanrsmith** [comment]
I will definitely help investigate this. I have also never seen it & so far haven't had luck reproducing it. A Plunkr that demonstrates the problem would be very helpful.

**Comment by jadrake75** [comment]
I am going to work on the Plunkr tomorrow morning.... stay tuned

**Comment by jadrake75** [comment]
ok it took a little bit of finagling to get it to show up.  I believe the critieria to make it show is 3 levels deep in the nav (possibly).  With 2 levels deep it was not showing up.  I apologize if the example is a little contrived..... basically you navigate to 

/top-level

Then pick one or more objects.  I have a global "count" that I increment when I activate the object's "view model".  So clicking on the green objects should increment this by 1 each time indicating they are being activated.  This is good.  The route would be /top-level/:name where name is the object id.  Now, below this each object has a series of "tabs" you can pick from.  This should do a child route to /top-level/:name/properties for example.  However clicking on this is causing the view model for :name (details-view.js) to get re-activated and increment the counter.

To show you need the three levels on Home I added a link to simply #/Object-2 which simulates the second object with the properties, attributes etc.  It does NOT increment the counter on clicking the navbar....

http://run.plnkr.co/xtMMs6C7zhgvpf8Z/

**Comment by jadrake75** [comment]
Incase the link above it acting up this one seems to be working smoother
http://embed.plnkr.co/e7njXl/preview

**Comment by gama410** [comment]
Any update on this?  I just ran into this problem also where the 'attached' method is called both for the parent and the child view (I have only two router levels)...

Seeing as there has been no update for 2 years on this bug, do you think it will be addressed?

**Comment by gama410** [comment]
Hello,

I now have to solve this problem in order to fix our navigation system so I took some time to try to understand why some nested views's activate method was recalled.

I made a minimum example with 3 views:

app with 2 child routes: bob & anne
bob with 2 child routes: bob & anne
anne with 2 child routes: bob & anne

They all have a default route with no child route.

When I navigate to #/bob/anne/bob/anne than navigate back once, I can see the activate method of anne & bob being called (instead of only bob).
When I looked at aurelia-router's _ findDeactivatable(plan, callbackName)_, I could see both viewModels added to the list of deactivable. Bob was added because its activation strategy was set to *replace* whereas anne had an activation strategy set to *invoke-lifecycle*.

Does anyone know why Anne's activation strategy was not set to *no-change* by default? When I added an activation strategy for all view models like below, it seemed to work ok : I didn't get the parent's activate method called when navigating back once...
`
  determineActivationStrategy() {
    return "no-change";
  }`

**Comment by TomDoig** [comment]
Hi, 

Just wanted to share that i'm still seeing this issue as well. In my example, I have a parent viewModel which loads data asynchronously in the activate callback and shares it between a number of simple child routes.

The parent's activate() is triggered once on first visit, but also re-triggered again each time the default child route (and only the default route) is activated, even if just navigating back from a sibling child route.

@gama410 's determineActivationStrategy() solution does prevent this issue. Do we know if this is the intended default behaviour?

**Comment by davismj** [comment]
@gama410 no-change is the activation strategy used on the parent route when navigating from one child route to another, for example. In any case, that sounds different from the bug on this thread. If you think there is a bug, please provide a repro. If it is this bug, please post here, otherwise, double check there isn't an open issue already and open a new issue if necessary.

@TomDoig This issue is not related to what you're seeing. The issue wasn't that activate was being called on the parent, but that the parent view was being rebuilt. Regarding activate being called on a parent, that's just how the router behaves. Feel free to open up an enhancement request to change this behavior if one doesn't already exist. If you are seeing this bug, please provide a repro. 

Thanks to you both!
