### ISSUE TITLE
ConfigureRouter issue

### ISSUE THREAD

**Issue by dpinart** [aurelia/router#119]
Hi,
I have a view model where I want to get router injected without setting up a child navigation. So, in the view model I've added following code snippet (typescript):
 public configureRouter(config: RouterConfiguration, router: Router) {
    this.router = router;
  }
the associated html view does not contain any router-view element.

I'm getting an Error :'Route not found' when navigating to this view

Am I doing something wrong?

thanks in advance

**Comment by EisenbergEffect** [comment]
To get a router without creating a new child router, have the router injected into the constructor through DI. This will get you the nearest parent router (or the app router).

**Comment by johnmanko** [comment]
Perhaps the articles/documentation should be updated to reflect that configuration of routes is required when using `configureRouter`. I ran into this issue today, and the error message doesn't describe the error clearly.

**Comment by EisenbergEffect** [comment]
Can you clarify that a bit more? I'm not sure I follow.

**Comment by johnmanko** [comment]
@EisenbergEffect sure. First, I can't find documentation for `configureRouter` at [aurelia.io](aurelia.io). In fact, I can't find a list of lifecycle methods a view controller can hook into.  There are references to to `configureRouter` in code examples, but information such as "adding a `configureRouter` method to your child-route class REQUIRES that routes be configured, otherwise you'll get an error routing to that child-route."  As a side note, it's either a bug that a `Route not found` error occurs, or it should be documented that it's the expected behavior. 

I would really like a list of hook methods I can add to a class.  And I'm not sure how the documentation is generated, but it should be trivial to link from one Aurelia class to another instead of having to hunt it down.  Just some thoughts.

**Comment by EisenbergEffect** [comment]
Have you read the Cheat Sheet in the docs? It has a list of component lifecycle events and a list of router lifecycle events. It also describes how to configure the router.

Can you explain why you would add a `configureRouter` method if you don't intend to configure routes?

**Comment by johnmanko** [comment]
@EisenbergEffect To answer your second question first, I was using `configureRouter` to get the router. I did know that I could inject it into the constructor, but I was taking a shortcut. :)

For your first question, is this an exhaustive list? BTW, I LOVE this framework, so don't think I'm complaining. :)

**The Component Lifecycle**
- `constructor()`
- `created(owningView: View, myView: View)`
- `bind(bindingContext: Object, overrideContext: Object)`
- `attached()`
- `detached()`
- `unbind()`

**The Screen Activation Lifecycle**
- `canActivate(params, routeConfig, navigationInstruction)`
- `activate(params, routeConfig, navigationInstruction)`
- `canDeactivate()`
- `deactivate()`

Others VM methods mentioned:
- `configureRouter`
- `determineActivationStrategy`


**Custom Attributes**
- `valueChanged(newValue, oldValue)`
- `propertynameChanged(newValue, oldValue)`
- `propertyChanged(propertyName, newValue, oldValue)`


**The Event Aggregator**
- `publish()`
- `subscribe()`

**Comment by EisenbergEffect** [comment]
That's the list, yes. However the event aggregator doesn't use any special hooks. Also not that "valueChanged" is a special instance of "propertynameChanged" for custom attributes, because they automatically get a "value" property.
