### ISSUE TITLE
Add router.removeRoute()

### ISSUE THREAD

**Issue by Siecje** [aurelia/router#129]
There is a ```router.addRoute()``` but currently no ```router.removeRoute()```

Use Case:

After login remove the login route.

**Comment by bryanrsmith** [comment]
Wouldn't you just need to add it again if the user logs out? Also, won't you want to redirect rather than showing an error on the login route? Instead of a `moduleId` you can provide a `navigationStrategy`, which is a function that can dynamically choose the module or action to take. This would let you select a login view if the user is unauthenticated, or redirect to another view if not.

We could support removing routes if there's enough demand, but it might take a bit of work. Route patterns are used to create a graph that is used to match incoming paths with a handler, and removing a path from that graph wouldn't be very easy. We'd probably need to just reset the router & re-register all the other routes. Personally I think that dynamically mutating the routes for an application make things hard to reason about, so I'd prefer to keep it as close to add-only as we can and instead try to improve features like `navigationStrategy` where needed.

**Comment by Siecje** [comment]
I would also like to remove the Login menu item in the nav and add another item.

Do you have any examples of how to do this?

**Comment by EisenbergEffect** [comment]
The navigation model is just an array. So, you can always remove the item from that.

**Comment by adriatic** [comment]
I found this discussion searching the whole galaxy for a good solution of the problem being discussed here - and found none. @bryanrsmith is right that removing the `login` route is not a good approach, so I would like to know how can I reuse the `login` route, where I would just like to change its title (from the word `login` to `logout` and vice versa), where the processing of the differences in the semantics could be easily handled in the view model.

Anyone with the advice from a good aurelia development practices collection?

**Comment by jfstephe** [comment]
FYI Removing the route from the list worked for me.
```

public closeRoute(route) {
    let indexToBeRemoved = this.router.navigation.indexOf(route);
    if (indexToBeRemoved >= 0) {
      this.router.navigation.splice(indexToBeRemoved, 1);
      this.router.refreshNavigation();
    }
  }
```

**Comment by jfstephe** [comment]
Spoke too soon. This doesn't work 100%.
Removing it removes it from the nav but not the list of recognised routes so the fallback isn't hit if you try to revisit the removed route.
I've raised [this issue](https://github.com/aurelia/route-recognizer/issues/28) in route-recognizer but it will affect this repo too.

**Comment by Zenuka** [comment]
Any news on this? I also like to dynamically add and remove routes...

**Comment by robscottnh** [comment]
I also would like to do this

**Comment by DickvdBrink** [comment]
bump, I think this needs te be reopened as the proposed solution doesn't fully work

**Comment by davismj** [comment]
I have yet to see a routing use case that isn't solved by multiple shells. Don't remove the routes, set a new shell with different routes.

http://davismj.me/blog/aurelia-login-best-practices-pt-1/

**Comment by Alexander-Taran** [comment]
@davismj can I steal your stuff for contrib?
