### ISSUE TITLE
Parameter Routes and Navigation

### ISSUE THREAD

**Issue by MeirionHughes** [aurelia/router#138]
The documentation says I can do parametrised routes: 
```javascript
{ route: 'doc/:name', moduleId: './doc', nav: true},
```
but how does the auto-generated nav menu work in this case? Is there a way to add/remove or bind-to context? i.e. something like:

```javascript
{ route: 'doc/:name', moduleId: './doc', nav: ['A', 'B', 'C']},
```
makes nav entries to "doc/A", "doc/B", "doc/C"? 

or something that can be passed around and updated?

```javascript
{ route: 'doc/:name', moduleId: './doc', nav: someObservableListOfDocs},
```

**Comment by bryanrsmith** [comment]
If you specify `nav: true` on a route with dynamic segments you must provide an `href` to be used in the nav menu.

```js
{ route: 'doc/:name', moduleId: './doc', nav: true, href: 'doc/A'}
```

There is currently no way to add more than once nav link per route, but you can always hard code them in the view, or use logic in your VM or custom attribute to generate them.

**Comment by kristianmandrup** [comment]
@bryanrsmith I don't understand how to use this. 

I've been trying this so far:

`{ route: 'screen/:id',  moduleId: 'screens/screen/display', href: 'red', nav: true,  title: 'Screen #1' }`

Then I get the error route not found `red`. But I thought the href was only for display purposes. So it seems to override the moduleId or wtf!? 

Having played around with Aurelia 1.0 the past few days, I feel the routing seems a bit "broken" (or very limited). I see potential, but I don't see how the current architecture scales to larger apps. 

Ideally you would have an app architecture reflecting a nested app hierarchy with a sub router at each level (ie. encapsulated mini apps). Like this one:

http://ilikekillnerds.com/2015/10/how-to-structure-an-aurelia-application/

I'm completely lost on when to use a child router vs. a router config extension in a normal view model. The docs still seem very "hello world"-ish still. 
How do we go beyond having one router in `app.js` and all the pages in the root... ??
Sorry for the rant ;)

PS: I'd love to help update the docs on routing once I get a better understanding. Yes, something like Ember approach is the way to go...

**Comment by kristianmandrup** [comment]
The docs for `href`  are gobbydygod to me...

`href` - is a conditionally optional property. If it is not defined then route is used. If route has segments then href is required as in the case of files because the router does not know how to fill out the parameterized portions of the pattern.

What does it mean `as in the case of files`  and `router does not know how to fill out the parameterized portions of the pattern` where? I assume for the url in the address bar and browser history etc?

**Comment by paulharker** [comment]
When experimenting with dynamic routes. this router.config works EXCEPT that the final two dynamic links do not generate an "isActive=True" when selected. Can you spot what I'm doing wrong, or is a bug?

`    this.routeMap = [
      { route: '', redirect: 'user-dashboard' },
      { route: 'user-dashboard', name: 'user-dashboard', moduleId: 'user-dashboard', nav: true,  title: 'Dashboard' },
      { route: 'favorites',      name: 'favorites',      moduleId: 'favorites',      nav: true,  title: 'Favorites'},
      { route: 'nav-menu',       name: 'nav-menu',       moduleId: 'nav-menu',       nav: true,  title: 'Nav Menu' },
      { route: ':id/settings',   name: 'settings',       moduleId: 'settings',       nav: false, title: 'Settings By Scope' },
      { route: 'paul',           name: 'paul',           moduleId: 'settings',       nav: true,  title: 'Paul',                href: '#/routing/paul/settings' },
      { route: 'charlie',        name: 'charlie',        moduleId: 'settings',       nav: true,  title: 'Charlie',             href: '#/routing/charlie/settings' }
    ];
`

**Comment by paulharker** [comment]
@bryanrsmith if you specify:
`{ route: 'doc/:name', moduleId: './doc', nav: true, href: 'doc/A'}`
`{ route: 'doc/:name', moduleId: './doc', nav: true, href: 'doc/B'}`
And then you try to create a navigator using "<li repeat.for='row of router.navigation'"> style menu, then the name property gets overwritten on all navigators in a weird way. That's why I opted to give teh route names something arbitrary in my previous example. Any ideas?
