### ISSUE TITLE
Custom pipeline step names not processed and child router steps cause child router failure

### ISSUE THREAD

**Issue by cpritchard** [aurelia/router#166]
Using the skeleton as a base started using some of the addPipelineStep features, but with error or unexpected behavior occurring even using a simple step such as...

class SomeStep {
	run(routingContext, next) {
		console.log('Running Step');
		return next();
	}
}

On the parent router the only steps that appear to work are 'authorize' and 'modelbind', the documentation states that any name can be passed in but they don't appear to get called unless they use the two names, For example a step attached with 'myStep' doesn't appear to actually get called. Adding three "authorize' steps does result in 3 calls. 

Then creating a child router with a pipeline step applied simply fails to initialize that class. "ERROR [app-router] Router navigation failed, and no previous location could be restored." and the child router fails to load.

**Comment by cpritchard** [comment]
Updating to 10.2 give a more usuable error that steps applied to children router is not supported, although it seems like this should be an option.

10.2 still results in custom step naming to not work as suggested by documentation.

**Comment by Alxandr** [comment]
As I've replied to you on [gitter](https://gitter.im/Aurelia/Discuss?at=55b29c53cfe8c23a6dfa7d04), you've misunderstood how custom pipeline steps work. First of all, it's by design that they are never to be added to child routers. This is due to several reasons. For once, it's generally not really practical to do at all, given that the routes are loaded **during** the pipeline (so, long after it's built). How you make sure that your pipeline steps only run in certain places is to add constraints to them, so they simply don't do anything when they aren't supposed to.

An excellent example of this is the authorize pipeline steps. They typically deny you access to any route that requires you to be authorized, but if the route doesn't require you to be authorized, it doesn't do anything at all.

Next, the names are simply "holes" in the pipeline where you can insert your own pipeline steps (with ease, and without having to deal with step indexes that might change without you knowing it). You can see the defined named steps here: https://github.com/aurelia/router/blob/master/src/pipeline-provider.js#L18-L30

If you add a step with any other name, it will simply be added to a list of named steps, but not included in any pipeline, because there is no named steps that has the same name. What `addPipelineStep('authorize', MyStep)` does is **not** add a authorize step, it adds a generic pipeline step (that can do anything) in the `authorize` slot (and you can have multiple of them). The names are just a convenience to make it easier to get the steps to run in the right order (which is quite important).

**Comment by cpritchard** [comment]
Based on Alxandr's comments it turns out this is all possible as the main router does fire on child router navigation and it is possible to access things from the child router from the parent. It is just not as simple as being able to apply steps directly to child routers as you do the patent router.

**Comment by iosulfur** [comment]
Those pre-defined names **need** to be in the documentation. Even if someone managed to find the page where the documentation for those step names could/should be, the steps names are not there _(as of the date of this comment)_.

http://aurelia.io/docs.html#/aurelia/router/1.0.0-beta.1/doc/api/class/RouterConfiguration
