### ISSUE TITLE
Adding parameter to child router causes navigation to fail

### ISSUE THREAD

**Issue by DuNuNuBatman** [aurelia/router#167]
Taking the navigation skeleton project and adding a parameterized route causes navigation to fail.

``` javascript
export class ChildRouter{
  heading = 'Child Router';

  configureRouter(config, router){
    config.map([
      { route: ['','welcome'], name: 'welcome',      moduleId: './welcome',      nav: true, title:'Welcome' },
      { route: 'flickr/:id',       name: 'flickr',       moduleId: './flickr',       nav: true, title:'Flickr' },
      { route: 'child-router', name: 'child-router', moduleId: './child-router', nav: true, title:'Child Router' }
    ]);

    this.router = router;
  }
}
```

Clicking on the Child Router link will cause the url to flicker, but it won't navigate to the page, it will say on the current page. I also tried adding id to the activate parameter.

``` javascript
  activate(id){
```

Also, there are no logs in the console to indicate any error.

**Comment by bryanrsmith** [comment]
You can't use nav: true on a parametrized route unless you specify an href to use in the nav link.

What version of the router are you using? There was a bug in a recent version that prevented errors from being logged to the console. The bug has been fixed in the most recent release. Could you check that you're up to date? If you already are I'll try to investigate tomorrow-- we definitely should be logging an error message when navigations fail like that.

**Comment by DuNuNuBatman** [comment]
Makes sense.
I was on 0.10.0 and just did jspm update and it pulled 0.10.2. The issue is in the error message!
Thanks, sorry for wasting your time. Odd I didn't have latest though, I just started playing around with this yesterday.

Thanks again.
