### ISSUE TITLE
Using URI Template (RFC 6570)

### ISSUE THREAD

**Issue by heruan** [aurelia/router#212]
[RFC 2560](https://tools.ietf.org/html/rfc6570) defines a URI Template syntax widely used in RESTful frameworks (e.g. [JAX-RS](https://docs.oracle.com/cd/E19798-01/821-1841/ginpw/), [Restlet](http://restlet.com/technical-resources/restlet-framework/guide/2.3/core/routing/hierarchical-uris), [Symphony](http://symfony.com/doc/current/book/routing.html)).

The syntax of routes changes slightly, i.e. `/user/:id` would become `/user/{id}` but there are many syntax options for matching the correct route (see the RFC).

There already exist JavaScript plugins to handle them ([uri-template](https://www.npmjs.com/package/uri-template), [uri-templates](https://www.npmjs.com/package/uri-templates), [url-template](https://www.npmjs.com/package/url-template)).

Why not using URI Template in Aurelia's router?

**Comment by EisenbergEffect** [comment]
I think this is a nice idea...however, as far as I can tell, all the linked libraries are focused on expanding the templates rather than pattern matching, which is what the router does mostly. So, we would need to write an entirely new matcher to support this change.

Since we hope to have the beta out in about 3 weeks, I don't think there's going to be time to do something like that. Especially considering this would be a massive breaking change.

@bryanrsmith You can comment further. Perhaps there is a way that we can use DI and some abstraction to allow our route recognizer to be swaped out. Right now we instantiate that directly, but maybe we should have a factory that can create instances of those and configure them? Then @heruan could replace it with his own. My guess is that this could be done post-beta without breaking anything. What do you think?

**Comment by bryanrsmith** [comment]
Yeah, we can do that after beta without breaking anything. We can probably
even factor out just the bits that care about syntax, too, so the matching
& generation logic doesn't need to be reimplemented.

I agree that it's too big a breaking change. The rails style syntax is much
more common in route patterns anyways.

**Comment by bryanrsmith** [comment]
Closing for now.
