### ISSUE TITLE
Add route parser for '$' as name/value pair preferably with-two way binding

### ISSUE THREAD

**Issue by corneliutusnea** [aurelia/router#215]
Hi,

I'd like to see (or add) support for a new specifier for routes `$` that will parse the url as a set of name=value pairs and feed them as an object in the activate. The name/value pairs could be delimited by a pipe "|".
Currently I ca do this `users/:id/detail` and get in the `activate({id:"1234"}` called but I want a bit more control so I'd like `users/$/` so I can do `/users/id=123|action=edit|highlight=firstName`
My activate should be then invoked with `{id=123, action="edit", highlight="firstName"}`.

Second step that would be even nicer would be to have a two-way bindable attribute:

````
import {UrlBind} from 'aurelia';
export class UserEditView{
    @UrlBind('id') id: string;
    @UrlBind('action') action: string;
    @UrlBind('highlight') highlightElementName: string;
}
````

Ideally these should be two way bindings so if my action in the view changes from 'edit' to 'activate' the url should automatically adjust (preferably without a deactivate/activate event) to `/users/id=123|action=activate|highlight=firstName`

Of course the parsing for the `$` should stop at the first '/' so this can be used with child routers
`/users/id=123|action=activate|highlight=firstName/address/[id=456|highlight=state|error='state is missing']/edit`

I think I can could do the first part of this and submit a pull-request but I'm not exactly sure where to start on the second one.

PS>> I don't want to use the "?" as that's supposed to go and the end and does not seem to be designed to be inside the route and be used in multiple child views.

**Comment by EisenbergEffect** [comment]
It looks like you are trying to re-implement query strings. Why don't you just use those?

**Comment by corneliutusnea** [comment]
Because the query string does not have a view selector. In the above example I can have id=1234 for one view and id=456 for the child view. With query strings I'd need to be extra careful to only have a single set of parameters that work for all views.

**Comment by EisenbergEffect** [comment]
I don't think we're going to add this out-of-the-box. It's very non-standard and would complicate a router that already has a ton of features.

As far as I know, there's nothing preventing you from doing this yourself though. You can just treat the entire segment as a single parameter in your route. You can then parse that parameter according to your own rules and handle it any way you want. You could even create a router pipeline step that automatically identified parameters in this pattern and pre-parsed them into the params object so it's all handled before it reaches the activate method.

In terms of data-binding, we can't do that in the router itself since that has no dependency on templating. But, implementing it in this way would actually complicate controllers because instead of having a single activate callback with all params, you would now have to have a callback for each param, each one being called separately, and you would need to sync route and state updates across all of them.
