### ISSUE TITLE
Regression - route-href sets wrong url on viewmodel from child route after page refresh

### ISSUE THREAD

**Issue by jebbench** [aurelia/router#306]
After updating to aurelia-router to beta.1.1.3 I'm having issues where child routes don't set the correct href on links when they are accessed directly (i.e. going directly to /parent-route/child-route) or the page is refreshed; loading the parent route and navigating to the child route works as expected.

It seems to be the same as previously fixed #169.

**Comment by EisenbergEffect** [comment]
@jedd-ahyoung @bryanrsmith Can you guys look into this. I think we should mark this as a high priority issue.

**Comment by bryanrsmith** [comment]
I think this is still #113. I don't know why it would have been working in a previous version, though.

**Comment by EisenbergEffect** [comment]
@bryanrsmith Would it be possible for you to tackle #113 next and attempt to move the calculation to a new earlier step in the pipeline?

**Comment by jedd-ahyoung** [comment]
@EisenbergEffect @bryanrsmith Looking at this, it looks like this is governed by the `_refreshBaseUrl` method in the router, which is called during `_commitChanges` in navigation_instruction.js. I don't see why this can't be called at the beginning of activate or even after the configure function runs.

The only thing I'm not sure about is that `_refreshBaseUrl` calls a method on the currentInstruction - `getBaseUrl()` - and I'm not sure when that instruction is created. If we can ensure that the router's currentInstruction isn't null, then we can move this call very easily.

Any thoughts?

**Comment by EisenbergEffect** [comment]
The instruction should be set up before the pipeline starts, so we should be good on that.

**Comment by jedd-ahyoung** [comment]
I've been looking into this more and I'll place my notes here.

BaseURLs in the router are dynamically generated at runtime by inspecting the fragment passed to the current navigation instruction. (This fragment comes from the history module, which will call `_loadURL` on the app-router). This is done because of the recursive nature of the routers and because of child routes. I don't think we can change this without sacrificing functionality.

`router.generate` is called from `route-href` in the templating-router library; this is guaranteed to be called after the router has been configured, but not before the router has been activated. Essentially, this means that the BaseURL isn't necessarily set when the routes are generated. @EisenbergEffect To your point, the instruction is indeed set up before the pipeline starts - but after configuration.

We have a few options:

1. Expand the `router.generate` method to build the baseURL for the specified route by either recursing child routers or by building a navigation instruction without dequeueing it. This could be expensive and we probably don't want to do this for every route-href on the page.

2. Make `route-href` only call `router.generate` after the router has been activated and a router instruction has been loaded. While this would work, this breaks the interface contract on the router and templating-router would have a dependency on app-router. We could alter the base router contract but I'm not sure that's a great idea.

3. Change the way that baseURLs are generated. I'm not sure, but instead of attaching the baseURL to a navigation instruction, perhaps we can recurse the router heirarchy to build the URLs. The issue with this is performance (possibly) and the wildcard route issue (is this even possible).

It's worth noting that any changes we make to this model should be able to support optional routes in the future, as well as other feature requests we've got in the queue.

I'll revisit this with more thoughts and edit this post accordingly. @bryanrsmith If you have any thoughts about this, they are very welcome. I'm attempting to build a better mental model of what's going on - it's frustratingly slow (I'm usually much better at this...) but I'll keep at it.

**Comment by heruan** [comment]
Any news on this? I'm experiencing the same issue with the latest router: binding to the `href` property in `router.navigation` produces wrong URLs.

**Comment by EisenbergEffect** [comment]
@jedd-ahyoung This relates to some of what you are working on correct? Any ETA on when you'll be able to finish that up?

**Comment by DrunkenInfant** [comment]
Is there any know workaround for this while it is being fixed? I tried adding a setTimeout in activate in which I set the data the routes-href use, but it doesn't seem to work.

**Comment by Jule-** [comment]
Same thing here, generated urls are missing the root at the beginning:
```javascript
config.options.pushState = true;
config.options.root = '/some/root/';
config.map([
  {
    route: 'someroute/:id',
    name: 'someroute',
    moduleId: 'someroute',
    nav: false,
    auth: true
  }
]);
```
```html
<base href="/some/root/">
```
```html
<a route-href="route: someroute; params.bind: {id: 'someid'}">Some Route</a>
```
This kind of configuration generates:
```html
<a href="/someroute/someid">Some Route</a>
```
and not:
```html
<a href="/some/root/someroute/someid">Some Route</a>
```

Afterwards appends strange behaviors: router fail to route and fallback staying on the current one or sometimes it succeed if you double click. And indeed it can not retrieve the route if you refresh the page.

**Comment by robbert229** [comment]
Any update on this? I am in the early stages of building a SPA and this is a critical bug that prevents me from making any more progress.

**Comment by EisenbergEffect** [comment]
We have identified the real issue over here: https://github.com/aurelia/templating-router/issues/46
If you would like to submit a PR, we an get the fix out immediately.

**Comment by vuorinem** [comment]
Is this possibly related to the fact that when generating routes in activate()-method using child router, the baseUrl is not updated and will generate wrong url? So for example using router.navigateToRoute() doesn't work in activate()-method.

Using attached() works fine, example:
https://gist.run/?id=8a73eca78d76065306dd459b64929ceb
