### ISSUE TITLE
is there a way to determine the previous route's name?

### ISSUE THREAD

**Issue by bebor** [aurelia/router#323]
is there a way to determine the previous route's name?

     i know that
`this.router.history.previousLocation`

     gives me the url for the previous route. means the one you go to when you do
`this.router.navigateBack();`

     but i need to know the routes name, the one o would need for doing:
`this.router.navigateToRoute(previouseRouteName);`

     any ideas?is there a way to determine the previus route's name?

     i know that
`this.router.history.previousLocation`

     gives me the url for the previous route. means the one you go to when you do
`this.router.navigateBack();`

     but i need to know the routes name?  --  the one o would need for doing:

`this.router.navigateToRoute(previouseRouteName);`

**Comment by EisenbergEffect** [comment]
Try `router.currentInstruction`. You should be able to get the information from that.

**Comment by chrisckc** [comment]
Hi, I have tried the suggestion and cannot find a way to get the previous route name or path.
I am using aurelia-router@1.0.0-beta.1.1.1 has this been fixed in the latest release? I am not quite ready to update everything yet.

This is what i have found:
`this.theRouter.currentInstruction.previousInstruction` is always null
`this.theRouter.currentInstruction.parentInstruction` is always null

i also tried:
`this.theRouter.history.previousLocation`
however the location returned is not the previous one, its the current one.

There really needs to be a property for the previous route *name* rather than the location so that the router can be controlled as it uses route names not locations.

Despite the previousInstruction and previousLocation not being available, the function `this.theRouter.navigateBack()` does work, i assume this is because its just controlling the browser back button?

The use case for needing the previous location is to allow the navigateBack() to be conditional depending on the previous route name. Also i need to account for when there is no previous route, if a page was launched directly from a link, the  navigateBack() function does nothing, so i need to know if this is the case and behave accordingly.

Btw. I am using the correct methods for navigating, either `this.theRouter.navigateToRoute(` or in the html using `route-href`

Thanks!

**Comment by EisenbergEffect** [comment]
@bryanrsmith This is related to the other issue I tagged you on this morning. I believe we have/had a way to do this. Can you investigate? There may have been a regression here.

**Comment by bryanrsmith** [comment]
7fa6e0b97370f08a4e3b1c08bad2ea1eded330f4 removed the `previousInstruction` at the end of the activation cycle to plug a memory leak. You will need to read the name of the previous route during activation and store it for later use. I believe this happened around version 0.13. I'm not sure why it would have worked with any beta version.
