### ISSUE TITLE
Change Page Title

### ISSUE THREAD

**Issue by genericuser-me** [aurelia/router#350]
```
 activate(params: any, route, navigationInstruction) {
       
        //route.navModel.router.title="test"; // This works, changes the title
         this.api.pull<Product>(params.id).then(items => {
                items.forEach(item=>
                {
                    if(item.id == params.id)
                        {
                            route.navModel.router.title = item.name;//// This DOES NOT work, changes the title
                        }
                });
                
         });
    }
```

Can anyone please help, why it doesnt change the router title when its within api call?

**Comment by AStoker** [comment]
Can you give more context? How is the router being used to display titles? The routes that are generated are different objects then routes defined, therefore you might be changing the title of the route, not not the navigational routes.

**Comment by genericuser-me** [comment]
Worked using return. here is the code:

 activate(params: any, route, navigationInstruction) {

        //route.navModel.router.title="test"; // This works, changes the title
         **return** this.api.pull<Product>(params.id).then(items => {
                items.forEach(item=>
                {
                    if(item.id == params.id)
                        {
                            route.navModel.router.title = item.name;//// This DOES NOT work, changes the title
                        }
                });

         });
    }

**Comment by AStoker** [comment]
Returning an api call in the activate will stop any further rendering or lifecycle callbacks until that promise is finished. So what was probably happening was the binding of the title wasn't taking place after the initial load. By not doing binding until after you have your data, you've solved your problem :) Otherwise, you'd have to give more examples of what you're trying to accomplish (including the html view).

**Comment by genericuser-me** [comment]
Yes :+1:
