### ISSUE TITLE
`addPipeline` not allowed on child routers

### ISSUE THREAD

**Issue by Roustalski** [aurelia/router#358]
Hi,

I have a parameterized route, e.g `...9000:/projects/:key/services`.

The `projects/` route configures a child router to go between several different sub-routes.
The VM that handles the parameter `:key` does a lookup to see if the key actually exists and shows a missing content section if the key is invalid without changing or redirecting the user.

Now, if the user hits `/services` sub-url using an invalid `:key`, I don't want to have to duplicate this logic to lookup the project and prep to show missing content.

I was thinking I could inject a pipeline step on the child router to consolidate the logic between the two VMs for the respective routes, but I get an error stating that pipeline steps aren't allowed outside of the root router.

What is the recommended approach for adding middleware to intercept route changes on child routes in the above scenario?

**Comment by EisenbergEffect** [comment]
We don't allow pipelines on child routers because the pipeline really operates on the aggregate navigation operation.

To solve this, you can still add a pipeline step to the root router. You can gain access to all the navigation instructions of all the child routers, make whatever inspections you want and take appropriate actions.
