### ISSUE TITLE
params vs. queryParams in route navigation seems broken 

### ISSUE THREAD

**Issue by don-bluelinegrid** [aurelia/router#387]
**I'm submitting a bug report**

* **Library Version:**
1.0.1

**Please tell us about your environment:**
* **Operating System:**
OSX 10.11.5

* **Node Version:**
4.4.7

* **NPM Version:**
3.10.3

* **JSPM OR Webpack AND Version**
 webpack 

* **Language:**
TypeScript 

**Current behavior:**
When making a call like this:
       this.router.navigateToRoute('login', {errorMessage: this.i18n.tr('error.sessionExpired')});

...I am seeing the following in the parameters to the target VM's activate() function:

navigationInstruction:
  {
    options:{}
    params: {},
    queryParams: {
      errorMessage:"Your session has expired or is invalid.  Please log in."
    }
  }

I see the passed-in 'params' data in the 'queryParams' object property and in the URL hash.

**Expected/desired behavior:**
The API shows this function documented like so:

navigateToRoute(): boolean
  route:string
  params:any
  options:any
Navigates to a new location corresponding to the route and params specified.

I would expect that if I pass a data object in to the 'params' argument, I will see this data object in the navigationInstruction's 'params' object property.  I do not see this.  I see the passed-in 'params' data in the 'queryParams' object property and in the URL hash.  This seems inconsistent with the documentation, and undesirable.

* **What is the motivation / use case for changing the behavior?**

Here is a typical use case:

In an Aurelia application, we make REST API calls.  At some point, our authentication token has expired, and I detect a 410 Unauthorized response in my response interceptor.  My response interceptor would like to automatically navigate to the login view in this case, passing along some data that indicates the type of error (session expired, server not available, etc.), so that the login view can conditionally display an appropriate inline error message.

The data that controls the display of the error message must be made available to the login view's VM, so that it can be set in scope as an available binding to the view template.  This data should not be passed as a queryParam and should not be visible in the URL/hash, since it is not routing data, it is VM data.

-----

What I'm reporting appears to be both a bug and an enhancement request.

The bug appears to be that the 'params' passed in the navigateToRoute() call end up in the queryParams property of the NavigationInstruction.  This seems incorrect.  And additionally, there appears to be a 'params' object in the NavigationInstruction, but no way to set data into that property.

The enhancement is to provide a way to pass data into the VM from a navigation call, as described above - either by fixing the bug so that the data appears in the 'params' object, or by providing another mechanism. 

If there is already an existing way to do this, please let me know.

Thanks,
Don

**Comment by StrahilKazlachev** [comment]
Can you share your **'login'** route pattern? Does it have a parameter `errorMessage` - something like this `login/:errorMessage`? If not, how are you expecting `errorMessage` to become a route parameter. From the API docs: 
- `navigateToRoute`
 - `params` - The **route parameters** to be used when populating the **route pattern**.

Sorry if I have misunderstood what you mean.

**Comment by don-bluelinegrid** [comment]
This is the route -
 -----
    config.map([
      { 
        route: ['', 'login'], 
        name: 'login',      
        moduleId: './login',      
        nav: false,
        errorMessage:'',
        title: this.i18n.tr('router.nav.login') 
      },


As I described in the report, I am looking for a way to pass param data from a call of navigateToRoute() to the route's VM - without putting data into the URL, either a path param or queryParam.

The use case that I provided above illustrates the need for this.  This functionality has been available for years in Angular's angular-ui-router module.  Some like that is needed here, because there are valid cases where some contextual data needs to be communicated from a caller of navigateToRoute() to the target VM, but is not appropriate to be in the actual route Url.

**Comment by paulharker** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; }  Try using the settings param


On Wednesday, August 10, 2016, 5:17 PM, don-bluelinegrid <notifications@github.com> wrote:


This is the route -
config.map([
  { 
    route: ['', 'login'], 
    name: 'login',      
    moduleId: './login',      
    nav: false,
    errorMessage:'',
    title: this.i18n.tr('router.nav.login') 
  },

As I described in the report, I am looking for a way to pass param data from a call of navigateToRoute() to the route's VM - without putting data into the URL, either a path param or queryParam.

The use case that I provided above illustrates the need for this. This functionality has been available for years in Angular's angular-ui-router module. Some like that is needed here, because there are valid cases where some contextual data needs to be communicated from a caller of navigateToRoute() to the target VM, but is not appropriate to be in the actual route Url.

**Comment by don-bluelinegrid** [comment]
@paulharker 

I think you may have misunderstood the report.

As I understand it, the 'settings' object is not actually a pre-defined part of the router API, it's an arbitrary/optional value set during router configuration.  How would one use such an object in a call to - navigateToRoute(routeName, params)?

Don

**Comment by paulharker** [comment]
Don, you are correct, as the settings property is flexible, it is statically created during route configuration. I am very interested in this kind of thing also, to please keep on it. As I understand routing today, I would accomplish this by having multiple routes or would use a route param with the idea that the response from the called for module is dependent on the error message, and therefore similar to calling up different page content if showing different details based on customer type when calling a customer details component.

**Comment by don-bluelinegrid** [comment]
I think you understand the situation and the use case better now -> pasing data along to a VM from a navigateToRoute(route, params) call, with the data *not* appearing in a route path param or querystring.

To make some similar to this work currently, I've had to do a major hack, in the activate() handler, to retrieve the passed params and then eliminate the unwanted querystring from the url, like this:

```javascript
  activate(params, routeConfig, navigationInstruction) {
    this.errorMessage = params.errorMessage;
    let hash = location.hash.substring(0,location.hash.indexOf('?'));
    if(hash && hash !== '') {
      let url = location.origin + location.pathname + hash;
      location.replace(url);
    }
  }
```

This is really something that should be handled by the routing module, and this is something that has been available in packages like angular-ui-router for a number of years.

Don

**Comment by EisenbergEffect** [comment]
If you pass a parameter to the the navigate api, it will attempt to place it in the route pattern. However, if your route pattern does not contain a parameter, the router does not know what to do with that data. In this case, it puts it in the query string. So, you can either declare a parameter in your route or allow it to be passed via the query string. It doesn't matter from the perspective of the `activate` callback because you will access the data the same way. If you don't want to pass it via the query string or define a route with a parameter (note that we support optional parameters now), then just stuff it in the DI container under a known key and then look it up in your activate method later. Or save it in some other shared storage service.
