### ISSUE TITLE
Enable route-href to reference child routes

### ISSUE THREAD

**Issue by dkent600** [aurelia/router#507]
**I'm submitting a question or feature request**

* **Library Version:**
1.3.0

* **Operating System:**
Windows 10

* **Node Version:**
v8.1.2

* **NPM Version:**
5.0.4

* **JSPM OR Webpack AND Version**
webpack 2.6.1

* **Browser:**
N/A

* **Language:**
TypeScript 2.4

I want to use `route-href` to construct an anchor tag href that references a child route.

In app.js, define a route to a parent view:

```
    config.map([
    { 
       route: 'parentview,
       name: 'parentview',
       moduleId: './parentview'
    }]);
```
In parentview.js, configure routes to child views:

```
    config.map([
    { 
       route: ['', 'childviewone'], name: 'childviewone', moduleId: './childviewone' },
       route:      'childviewtwo',  name: 'childviewtwo', moduleId: './childviewtwo' }
    ]);
```

I have found no way to use `route-href` to construct an anchor tag href that looks like "parentview/childviewone" or "parentview/childviewtwo".

This seems like a simple and potentially common scenario.  Am I missing something or is this a feature that should be part of the framework?  

I found the following possibly-related issues.

https://github.com/aurelia/router/issues/89

https://github.com/aurelia/router/issues/90

**Comment by jemhuntr** [comment]
Bump. Would be great if there was some way to reference child routes, maybe something like:

```html
<a route-href="route: parent-route/child-route;">Inner Link</a>
```

which ideally would activate the named route `parent-route` and look into its inner router for a `child-route`.

**Comment by Alexander-Taran** [comment]
@jemhuntr  you might want to check out this plugin https://github.com/aurelia-contrib/aurelia-router-metadata

**Comment by jemhuntr** [comment]
Thanks @Alexander-Taran, I've seen that plugin and although it's very tempting to use it, it's hard to commit to using a third-party plugin for a feature as basic as navigating to child routes. As much as possible, I'm trying to avoid maintenance bottlenecks down the line since I'm pretty sure the API for this will still significantly change once the functionality hits core.

In the end I've decided to just hardcode the URL paths on `href` instead of using `route-href`.

Right now I'm just hoping that this feature (among other router-related enhancements) is already being considered on the experimental aurelia rewrite at [aurelia/experiment](https://github.com/aurelia/experiment). :)

**Comment by EisenbergEffect** [comment]
@jemhuntr For the experimental work, we're still figuring out core pieces, so we haven't gotten to something higher level like the router. I do think, when we get there, the vNext router will get a substantial set of improvements.

**Comment by jemhuntr** [comment]
@EisenbergEffect Sounds great! Looking forward to vNext :)
