### ISSUE TITLE
Make navigation to urls starting with / navigate from root

### ISSUE THREAD

**Issue by Alxandr** [aurelia/router#52]
When navigating to urls that start with a `/` (like `router.navigate('/foo')`), it should navigate from the root, not the current router.

Ref #51

**Comment by bryanrsmith** [comment]
I agree. I think this relates to a few issues with paths in `navigate` and `generate` right now. Fragments returned by `generate` should always do what you expect when you pass them directly to `navigate` on the same router, but I don't think that's the case now.

1. `generate` currently always returns paths that start with a slash, even when the router that generated them is a child and the path is not absolute. This should work fine with `navigate` (on the same router) because of the issue you note, but it probably won't work right for any other use.
2. `generate` can fall back on its parent router if the named route isn't found, but if this happens the generated path will be relative to the router that generated it, not relative to the current router. `navigate` always prepends the current router's baseUrl, so this won't work right.
3. `generate` with `{ absolute: true }` should generate a complete path safe for inclusion in an anchor href, including a hash if not using pushstate. `navigate` should recognize such absolute paths and behave as expected instead of assuming the path is relative to itself and constructing a potentially invalid path.

What if `generate` always returns absolute paths, and `navigate` becomes more forgiving in what it accepts, resolving the fragment to a valid absolute path before handing it off to history? I think this would make generated fragments valid across the whole app, and might make it easier to navigate to any point in the app regardless of relation to the current router.

@EisenbergEffect Any thoughts on this? Why did you reject the proposal for `navigate` to treat fragments starting with slash differently in #51? I can work on this if we can hash out the desired behavior.

**Comment by EisenbergEffect** [comment]
@bryanrsmith I didn't have time to consider all the implications during the last release. That's main reason I didn't include that fix. You are doing great work to improve this aspect of the router. I'd be happy to take a PR to improve all this if you want to put together a final recommendation for me to review.

**Comment by bryanrsmith** [comment]
@EisenbergEffect Perfect. I'll work on a PR. Quick heads up, though-- my wife and I are expecting our first baby any day now. If I suddenly disappear for a few days or a week it's not because I'm abandoning the work :-)

**Comment by EisenbergEffect** [comment]
Congratulations! That's awesome.
