### ISSUE TITLE
"router:navigation:complete" gives wrong nav instruction (or should trigger twice) on redirects?

### ISSUE THREAD

**Issue by deap82** [aurelia/router#553]
**I'm submitting a bug report**

* **Library Version:**
aurelia-router, 1.4.0 and current as reproduced in gist

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
8.9.0

* **NPM Version:**
5.5.0

* **JSPM OR Webpack AND Version**
JSPM 0.16.53

* **Browser:**
all

* **Language:**
all

**Current behavior:**
I'm using the EventAggregator to subscribe to the router:navigation:complete event, and I ran into a problem when wanting info about the current navigation instruction on the initial redirect that happens for my default empty string route.

I found that as a workaround I can access the actual navigation instruction from router.currentInstruction, but as the event name is "...:complete" it seems to me it should give me the final nav instruction OR the event should trigger twice; once for the redirect instruction and once for the final destination.

I have illustrated the issue in this gist: https://gist.run/?id=3e62bafe32d83b6e27cc31e0465519c7

**Expected/desired behavior:**
* **What is the expected behavior?**
The eventargs for event router:navigation:complete should give the final nav instruction, or trigger twice when a route is a redirect or when a route module uses the router to navigate to another module.

* **What is the motivation / use case for changing the behavior?**
It's what I expected given the name of the event I'm listening to.

**Comment by davismj** [comment]
@deap82 I understand why you would want to do this ,and I think there could probably be better handling for this case, such as a warning or better documentation.

In the meantime, try the following pattern instead. First, instead of redirecting in `activate`, redirect in `canActivate`. The idea is that once `activate` starts, the routing needs to complete. `canActivate` is the right place to cancel and redirect navigation.

Second, return `new Redirect('view')` from `canActivate`. The `Redirect` object is a special set of navigation commands that the router understands.

Working example:
https://gist.run/?id=aa989d4ab2a10c559fcd526a32fe47b1

Thanks for the report.

**Comment by deap82** [comment]
Sorry for coming back to this so late, but for anyone coming here I'd just like to point out that I'm not really using the event to do a redirect, and even the "Working example" from davismj has the issue I'm actually reporting;

Namely that the eventargs of the complete event does not contain the same navigation instruction as router.currentInstruction when the navigation complete event is triggered from a redirect.
In the gist(s) I would expect the logs in app.js->routeNavigationCompleted to output the same navigationInstruction object.

**Comment by JontyMC** [comment]
I'm hitting this issue now. Is there any way to get the proper navigation instruction for the redirection from a router event?

**Comment by JontyMC** [comment]
Ah, I see now I can just use the current router instruction
