### ISSUE TITLE
Nested states and nested views

### ISSUE THREAD

**Issue by zzapal** [aurelia/router#56]
This week my team and I finished big project in Durandal and see some shortcomings with router and view composition that angular's ui-router's nested states and nested views would would solve.

Angular 2 is going in wrong direction by resigning from two way databinding, so the only choice is to try to convince you to implement nested states and view like ui-router does :).

Any luck implementing this?

**Comment by zewa666** [comment]
Hi there, could you provide an example that you felt was hard to achieve with the router? Maybe also just a pseudo code for how you'd do that with UI-Router? It's always easier to decide upon such things with a concrete example and use case

**Comment by zzapal** [comment]
Here's example, simplified layout we have.
http://run.plnkr.co/3KND9Rcx8oUvlUwo/

On left there's normal menu which changes whole right section. In this right section we've got tabs. Each tab currently is separate durandal widget. In each tab there's some data organized in separate panels which can be edited.

Each panel has it's own edit lifecycle - when you click Edit it's layout changes to a form with Save button. After saving layout changes to list. Currently we're doing this by managing the flag isEditing in each widget for panel (form + list).

Problem:
- some data is shown in list, but is not being edited and each widget needs to know it can be change to edit mode or display mode + some data-bind="if: ..." to show/hide sections
- we can't efficiently put links on different screens to for example to page with mark and model editing section and (on yet another screen) link to page with mark and model display section
- well, we could, but we would need to create separate URLs for each page, tab, section and edit/display mode - which is a lot
- add to that bussiness needs to make URL point to first tab on given page with all sections in display mode, but be able to place a button somewhere to open section in edit mode.

As I understand, with ui-router I could:
- create URL /details for one state
- create nested states without URL for tab number 1, tab number 2, tab number 3
- under tab number 1 create nested states for email display section, for email edit section, for mark/model display section, for mark/model edit section

Then going to /details would open details page with tab number 1 open and both email and mark/model sections in display mode.
Linking to state for "email.edit" would show details page with tab number 1 open, email section in edit mode and mark/model section in display mode.
Then going to "mark/model.edit" state would show details page with tab number 1 open, email section left in edit mode and mark/model changed to edit mode.


What's even more interesting is that by just changing ui-router's state configuration I could move mark/model section to different tab.

All of this is of course possible with URLs for each of these, but requires a lot of URLs, parsing them, hard-coding sections in given places in HTML. Then, to move section between tabs we would need to remove widget section from one tab, create it in different tab, then change URLs in routes and change all <a hrefs linking to that URL. So, we simply told business - it can't be done :/.

**Comment by amitaibu** [comment]
named views is indeed a needed feature when dealing for example with dashboard pages. Here's [some explanation](https://github.com/angular-ui/ui-router/wiki/Multiple-Named-Views) from Angular's UI router

**Comment by EisenbergEffect** [comment]
@amitaibu We call these "siblings" and I'm happy to say that it's already been supported since we first announced Aurelia :) (It just hasn't been documented.) For your route config, instead of having a moduleId, you add a viewPorts property. That is an object that maps keys to route configuration. Something like this:

```
{
route:'some/route',
  viewPorts = {
    'left-side': {
      moduleId: 'some-module;
    },
    'right-side':{
      moduleId:'another-module'
    }
  }
}
```

Then, in your view, you need multiple `router-view`s. Name each one the same as the view port's keys. When the route is matched, the proper module will be loaded into each router view.

**Comment by amitaibu** [comment]
:+1: 

@EisenbergEffect should I create a PR to add this info to this repo's readme?

**Comment by EisenbergEffect** [comment]
@amitaibu If you would like, send a PR to the documentation repo and add a section there to the documentation on the router.

**Comment by amitaibu** [comment]
Will do, thanks.

**Comment by EisenbergEffect** [comment]
Closing since this isn't an issue.

**Comment by kristianmandrup** [comment]
Has this been documented? Super important feature IMO for any app beyond a "toy app"!!!

**Comment by bryanrsmith** [comment]
@kristianmandrup http://aurelia.io/docs.html#rendering-multiple-view-ports

Looks like the markup is broken in the current version of the docs, but it's fixed on master. https://github.com/aurelia/documentation/blob/master/English/docs.md#rendering-multiple-view-ports

**Comment by kristianmandrup** [comment]
When will we see a revamp of the docs? On the 1.0 release? I hope that release is reals soon (within next couple of weeks). Starting to feel that Aurelia is stalling indefinitely... (easy for me to say :P lol)

**Comment by EisenbergEffect** [comment]
We definitely aren't stalling. In the last 10 days we have:

* Introduced a new cross-loader plugin system
* Refactored view loading to enable both text and html import-based loading
* Introduced new view engine hooks
* Introduced a new view resource plugin system
* Implemented requiring CSS per view
* Implemented JavaScript-less custom element via requiring .html files in views
* Added API doc generation to all libraries
* Moved towards a unified linting model for all libraries
* Improved existing bundling and worked towards text view and css bundling
* Improved the quality of many generated d.ts files across libraries
* Fixed lots of bugs
* Made significant progress on the new documentation app
* Made significant progress on our new benchmarking tool
* and more

So, we are definitely moving ahead. With the regard to the docs, we are moving ahead on several fronts there: API doc generation and the doc viewer. The new docs will be part of the beta release, which we are hoping will be late September or early October we hope. We can't be entirely concrete on this, because being an open source project based on community contributions, we can't guarantee a steady burndown rate. However, everyone is working hard and things are moving along rather significantly. No signs of stalling from my perspective.

**Comment by nomack84** [comment]
@kristianmandrup if you want to see an stalled project, take a look a angular2, 35 alphas an counting, also, between alpha releases they have tons of BC breaks and they haven't yet a clear date for beta releasing. Besides the fact that they are a bigger team with much more resources...

**Comment by kristianmandrup** [comment]
Sure, the Aurelia team is AWESOME!!! 'm not even looking at the Angular 2 camp since end of last year after the announcement, when I looked at the hideous syntax they had come up with for their "templating system"... 

Anyhow, just feel that the beta and 1.0 release keep being pushed out. I'd rather have a 1.0 that is not "feature complete" but with good docs, easy to get started and sufficient for 80-90% of my needs. 
Why I spent a lot of time building a really powerful aurelia generator: [aurelia-ts](https://github.com/kristianmandrup/generator-aurelia-ts)

I believe that as soon as you have that beta or 1.0, devs will start to abandon Angular 2 and jump ship to Aurelia, in droves ;) Cheers!!!

**Comment by EisenbergEffect** [comment]
We are working towards it. The big piece is the documentation, which requires a lot of work to get right. Once that is ready, then we will go beta most likely.
