### ISSUE TITLE
Redirect in child router (navigation strategy), when parent is using navigation strategy

### ISSUE THREAD

**Issue by balazsmeszegeto** [aurelia/router#588]
**I'm submitting a bug report**

* **Library Version:**
1.3.0 (also tried in 1.5.0)

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
9.2.1

* **NPM Version:**
5.7.1

* **JSPM OR Webpack AND Version**
JSPM 0.16.53

* **Browser:**
all (Chrome 64 | Firefox 59 | Edge 41 )

* **Language:**
ESNext

**Current behavior:**
Redirecting in child router using navigation strategy is not working, when parent router also has a navigation strategy defined.

https://gist.run/?id=087cf483ccb4476a3c7cb8a76a49823e
If you uncomment app.js/line 27, navigation to rooms route stops working. The Url is being updated correctly, but the view models are not being loaded into the corresponding viewports. I could not perfectly localize the bug, but the viewport plan is empty. I think it is nearby AppRouter._dequeueInstruction method

**Expected/desired behavior:**
Redirect works in child router, even if parent route has used navigation strategy

* **What is the motivation / use case for changing the behavior?**
Dynamic redirect based with navigation strategy, when parent route is using a navigation strategy

**Comment by Alexander-Taran** [comment]
@EisenbergEffect something to consider for vNext?

**Comment by balazsmeszegeto** [comment]
If you point me to the right direction, I'm happy to contribute with a PR

**Comment by davismj** [comment]
This bug is a race condition. Adding the navigation strategy handler adds one too many items to the wrong queue, which causes the navigation pipeline before the navigation instruction is created.

The source of the bug is on [history-browser/index.js#L235](https://github.com/aurelia/history-browser/blob/master/src/index.js#L235): 

```javascript
_loadUrl(fragmentOverride: string): boolean {
  let fragment = this.fragment = this._getFragment(fragmentOverride);
  
  return this.options.routeHandler ?
    this.options.routeHandler(fragment) :
    false;
}
```

`this.options.routeHandler` refers to [Router.loadUrl](https://github.com/aurelia/router/blob/master/src/app-router.js#L42), which returns a Promise. Once the promise is disregarded in the history-browser code, the race is on. 

The right thing to do would be to

1. Correct the typings to return a promise,
2. propagate the promise upwards, and
3. await the promise in the Router.processResult function, [here](https://github.com/aurelia/router/blob/master/src/app-router.js#L201).

You'll end up with something like this:

```javascript
function processResult(instruction, result, instructionCount, router) {
  if (!(result && 'completed' in result && 'output' in result)) {
    result = result || {};
    result.output = new Error(`Expected router pipeline to return a navigation result, but got [${JSON.stringify(result)}] instead.`);
  }

  let finalResult = null;
  let generateNavigationInstruction = null; 
  if (isNavigationCommand(result.output)) {
    generateNavigationInstruction = result.output.navigate(router); // grab the promise
  } else {
    finalResult = result;

    if (!result.completed) {
      if (result.output instanceof Error) {
        logger.error(result.output);
      }

      restorePreviousLocation(router);
    }
  }

  // await the promise, or proceed immediately if no promise
  return Promise.resolve(generateNavigationInstruction).then(() => {
      return router._dequeueInstruction(instructionCount + 1)
    }).then(innerResult => finalResult || innerResult || result);
}
```

The most time consuming part of any fix is good working tests. Submitting the best tests possible will help me process your PR quickly!

Thanks for reporting this issue.

**Comment by balazsmeszegeto** [comment]
Sure, I'll check that :)

**Comment by balazsmeszegeto** [comment]
Should I create a PR in browser-history and _then_ in router? Or is it okay to send in parallel?

**Comment by Alexander-Taran** [comment]
@balazsmeszegeto you can send in parallel with mentions of each other.. that one depends on another if that's the case

**Comment by balazsmeszegeto** [comment]
Sure. I cannot promise to be ready during the weekend, but I'll work on it next week

**Comment by Alexander-Taran** [comment]
@balazsmeszegeto don't promise anything.. It ends up badly usually (-:

**Comment by balazsmeszegeto** [comment]
@Alexander-Taran I've sent in the PR last week as promised :) When can I expect some review?

**Comment by Alexander-Taran** [comment]
@balazsmeszegeto  I see that  @davismj assigned himself. Let's wait and see.
