### ISSUE TITLE
authorize pipeline step should occur before instantiating the view.

### ISSUE THREAD

**Issue by Zoltu** [aurelia/router#60]
As a developer, I would like certain parts of my application to be able to make assumptions about authentication and let the navigation pipeline deal with ensuring authentication.  In order to do that however, the `authorize` pipeline event must evaluate before instantiating the view, otherwise it is possible for my views to be instantiated for unathorized users.

This problem is compounded by the fact that if an exception is thrown from a view constructor, all routing fails.

Currently, if I have a class hooked up to the `authorize` pipeline step that always redirects, the view that the route would have routed to is still instantiated every time.

```js
router.configure(config => {
	config.addPipelineStep('authorize', AuthorizeStep);
	config.map([
		{ route: '', moduleId: './logged-in' },
		{ route: 'login', moduleId: './login' }
	]);
}
```

```js
export class AuthorizeStep {
	static inject() { return []; }
	constructor() {}
	run (routingContext, next) {
		if (routingContext.nextInstruction[0].config.route == 'login')
			return next();
		return next.cancel(new Redirect('login'));
	}
}
```

```js
export class LoggedIn {
	constructor() {
		console.log('This should be unreachable, but it is!');
	}
}
```

The use case I currently have for this is in the constructor of my VM, I do some things that require authorization.  The `authorize` pipeline step handler is setup to ensure that the user will never see the page if they are not authorized.  However, the VM is constructed before the `authorize` pipeline step is executed which means logic in the constructor will fail.

I can, of course, work around this by moving my logic out of the constructor but this is not only counter intuitive, but it also means my class's complexity goes up because I can no longer assume that the class is always instantiated in a state that is reasonable for the VM (authenticated).

As a side note, it also seems wasteful to construct the VM if it isn't going to be used, especially since a VM constructor may do expensive operations that will simply be thrown away as soon as the authorize step fails.

**Comment by Zoltu** [comment]
After some further discussion on gitter and viewing https://github.com/aurelia/router/blob/master/src/pipeline-provider.js, I believe that `createRouteFilterStep('authorize'),` should be moved up above `LoadRouteStep,` in the pipeline.

**Comment by EisenbergEffect** [comment]
It cannot be moved up because all the instances that might need to be authorized would not have been created then.

**Comment by EisenbergEffect** [comment]
Bare in mind that only the view-model's constructor is called. Nothing else happens. The view itself is only created if the route can be fully activated.

**Comment by Zoltu** [comment]
> all the instances that might need to be authorized would not have been created then

That was the entire point.  The authorization code shouldn't be depending on the thing that needs to be authorized and constructing the VM before authorizing is very counter-intuitive.  It means you are creating a VM that will never be accessed, just constructed and thrown away due to the authentication system saying, "No, it is not okay to create that view at this time, the user is not authenticated yet."

**Comment by EisenbergEffect** [comment]
You can add a step earlier in the pipeline and do whatever you want whenever. Part of the design is so that you can do that if you need or want to.

**Comment by Zoltu** [comment]
Yeah, I won't push back too hard on this issue because of that extensibility.  However, I still question the value of having `authorize` occur after VM construction.  I struggle to come up with a compelling story where the user would benefit from this and as it stands now is counter-intuitive.

Speaking from experience, this cost me about an hour of troubleshooting to realize what was happening (VM constructor was assuming authorization had passed), then it took me understanding that the pipeline allows for additional extensibility points followed by learning at what point in the pipeline VM construction occurred at.  Figuring this all out took quite a while, though that is largely due to lack of available information at the moment.

**Comment by bfil** [comment]
@EisenbergEffect I came across this issue today after adding an `authorize` step.

I can see a `router:navigation:complete` event triggered for the view that is not supposed to be reached, and a subsequent one for a login view for instance (this also causes layout flickering in my app because of the double navigation complete event raised).

You said it's possible to add a step earlier on the pipeline, can you share some info about how to do that?

**Comment by davidpeden3** [comment]
This is the [feature](https://github.com/aurelia/router/pull/30) that was added and here is the corresponding [documentation](https://github.com/aurelia/documentation/commit/6722bd9b95f66e22087c0a55349a3a75ddc98d9a).

What is unclear is if you can actually add your own custom steps at any arbitrary point in the pipeline, rather than piggybacking on existing steps as documented above. I also found this [conversation](https://gitter.im/Aurelia/Discuss?at=54d90d3c938f0fd216cf132c) which suggests that you can manipulate the [steps array](https://github.com/aurelia/router/blob/master/src/pipeline-provider.js#L18) directly.

I also ran into the same issue that you did, @bfil, and decided to go with the flow using `authorize` rather than naming my own custom `authenticate` step even though it is more technically accurate for what I'm doing in my pipeline step. I will likely revisit this in the future, especially if the API is improved.

**Comment by bfil** [comment]
Thanks for the info @davidpeden3 

The manual pipeline crafting does not look like a great approach though.

I'm trying to see if I can achieve my end goal with a base view and a canActivate() method on it instead for views that need authentication.

It would be good to know if any effort will be put to improve this API, I agree with @Zoltu, the way it behaves now feels very counter-intuitive. Especially the fact that a navigation complete event is raised by the router even though the instruction is cancelled by a pipeline step.

**Comment by bfil** [comment]
To help anyone else trying to add a step to the pipeline at a different position, here's an example that is working for me (adds the authentication step after the LoadRouteStep and before the authorize):

```javascript
@inject(Router)
export class App {
	constructor(router) {
		router.pipelineProvider.steps.splice(2, 0, AuthenticateStep);
	}

	configureRouter(config) {
		// ...
	}
}
```

The `router:navigation:complete` is still raised for the view even if the step is executed before everything else in the pipeline and the next instruction is cancelled with a redirect, might be worth opening a separate issue for this?

**Comment by bfil** [comment]
I've opened pull request https://github.com/aurelia/router/pull/97 to solve the issue with the wrong navigation event being raised.

This actually solves my original problem, using the standard `addPipelineStep` results in no flickering (that was caused by some of my logic in handling the navigation complete event to recreate the layout based on the view)

**Comment by sylvain-hamel** [comment]
+1 on the request to make move the authorize step earlier in the pipeline.

**Comment by kristianmandrup** [comment]
+1 to improve this :)

**Comment by thomas-darling** [comment]
Just ran into this one too :-/

Parts of my application needs info about the currently authenticated user, so I thought I'd just register my `User` instance in the container once the user signs in, so it can be easily injected into the view models that need it. However, that failed, as it relied on the assumption that the `authorize` step would ensure those views are never instantiated until the after the user signs in, and thus after the `User` is created and added to the container.

There are other approaches, of course, but it feels like this is something that should have worked.
The route configuration really shouldn't be so this tightly coupled to the view models...

**Comment by kristianmandrup** [comment]
@thomas-darling I think the router definitely needs to be re-thought, re-engineered and re-implemented in order to be more flexible and composable to suit any scenario. 

Would be nice with a simpler router engine alternative to build from, based on Router and Route components similar to React Router v4, instead of building a static Router model from a fixed configuration. Just my 2 cents on it.

Some possible starting points and inspiration:

https://github.com/visionmedia/page.js
https://github.com/tj/react-enroute

**Comment by davismj** [comment]
I think a good point has been made here. The authorize step doesn't need to know anything about the specifics of the route it is loading. It's more meant to be a global can activate, which is probably why it landed before the local can activate step, but it could be moved before the load route step. 

Unfortunately, at this point it would be a breaking change to change and I'm not sure we want to break anything for this particular case. 

@thomas-darling I don't have access to a computer at the moment but I'll try to get you a quick example of a better way to register your user object with the DI. The best approach would be to inject a function or class able to retrieve the user, and then retrieve the user when you need it. I typically inject an AuthService class with a getUser() method. You could also use container.registerInstance(User, getUser()). Injecting Lazy.of(User) is a third option that will inject a function that will ask for the object from the container, so that will be the quickest way to solve your problem immediately. 

@kristianmandrup We are currently re-thinking, re-engineering, and re-implementing the router to be more flexible and to suit any scenario. We'd love to hear your ideas about what use cases ought to be supported and how they should be implemented here: https://github.com/aurelia/aurelia/issues/67

**Comment by thomas-darling** [comment]
@davismj Thanks, but no need - already worked around it by injecting a service instead. I was just really surprised that this didn’t work - although I should have known, given how child routers are configured...

What really needs to happen here, is a separation of the route configs from the view models, such that the information needed to generate and recognize routes is available before the view models are loaded - as in, even before the bundles that contain them are loaded. The technical stuff, such as module ids and nav instructions, should remain in the view models.

Separating things this way, the authorize step could receive a model representing the  recognized route segments, including any custom configuration options specified for them, and use that to determine what should happen 🙂

**Comment by davismj** [comment]
Technically, this is the case today. The only reason why it might not be possible is to support child routers.

> a separation of the route configs from the view models, such that the information needed to generate and recognize routes is available before the view models are loaded

It's hard to know how to do that well. The only way to support this case is to have route configurations completely separate. It's an idea we're playing with.

Part of the problem is that people are using child routers. We could solve a great deal of problems just by removing child routers. A lot of people are using child routers when they don't need to. They might have routes like this

```javascript
// parent
{ route: 'foo', moduleId: 'parent' }

// child
{ route: ':id', module: 'child' },
{ route: ':id/edit', module: 'child' },
{ route: 'preview', module: 'preview' }
```

When they could have just written.

```javascript
{ route: 'foo/:id', module: 'child' },
{ route: 'foo/:id/edit', module: 'child' }
{ route: 'foo/preview', module: 'preview' }
```

However, I know removing child routers would be perceived as a complete step backwards. So we have to figure out how to work around the limitations imposed by a child router scenario while supporting a broad array of uses cases for child routers. We've solved this problem so far in ways like the root of this issue, by imposing limitations elsewhere.

**Comment by brandon-marginalunit** [comment]
I'm running into this same issue and I can't figure out how to add a step earlier in the pipeline, before the view would be constructed.

@EisenbergEffect you mentioned this was possible:
> You can add a step earlier in the pipeline and do whatever you want whenever. Part of the design is so that you can do that if you need or want to.

But according to the docs:
> The default pipeline slots in order are authorize, preActivate, preRender, and postRender

It does also say:
> You can create your own pipeline steps using addPipelineStep, but the step's name must match one of the default pipeline's slots.

But does that not just put the new step into one of those existing slots? How do I put something _before_ `authorize`?

**Comment by EisenbergEffect** [comment]
@brandon-marginalunit The router is designed with a standard set of "slots" that you can add steps into. It is possible to add steps manually, as long as you are careful not to break the expected pipeline behavior. Have a look here:

https://github.com/aurelia/router/blob/master/src/pipeline-provider.ts#L49

The `PipelineProvider` contains all the steps that make up a navigation flow. So, you can push something custom in there, if you need.
