### ISSUE TITLE
Set 'routeConfig.navModel.title' cannot change title except in canActivate();

### ISSUE THREAD

**Issue by boogunote** [aurelia/router#69]
`routeConfig.navModel.title` only can be set in canActivate(). Hope it can be changed in other place.

**Comment by bryanrsmith** [comment]
I'm able to set it in both `canActivate()` and `activate()`, as long as the change happens before the router commits. That is, if you set `routeConfig.navModel.title` asynchronously, you must return the promise from `activate` so the router knows to wait for your change.

@boogunote Where is it you're hoping to set `routeConfig.navModel.title`? Can you post the code that'd like to work?

@EisenbergEffect It does seem like we're missing support for a valid use case here. Using aurelia/app-contacts as an example, say I wanted to activate the details view immediately and show a loading indicator while the contact was fetched. I could do that by not [returning the promise in activate](https://github.com/aurelia/app-contacts/blob/master/src/contact-detail.js#L14), but then I wouldn't be able to update the document title when the data loaded because the router would have already run the `CommitChangesStep`. How do you feel about supporting delayed title updates?

**Comment by EisenbergEffect** [comment]
@bryanrsmith I definitely think we should fix this. I haven't looked into it to see how much work it would be. If you want to investigate further, let me know what you think would be a reasonable solution.

**Comment by bryanrsmith** [comment]
In the current implementation the navModel is a plain object property of the route configuration. We're allowing view models to mutate the config.navModel, and then reading that data in the final step of the navigation pipeline. 

I propose separating the navModel from the route config. Other parts of the router use it to store state, such as `isActive`, which I think makes it more than just a "config" sort of thing. This would be a breaking change because route configs can provide their own navModel property. I don't think we document that anywhere, and `Router.add` copies all the navModel data off the top level config properties. I'd guess that's the API that most are relying on since it's what all the docs and examples use.

Once we pull navModel off the config we can create a `NavModel` class that holds a reference to the current instruction or context. Then we can move the title generation and setting logic into a `setTitle` or `title` setter that can perform the update outside the scope of the navigation pipeline. It would still need to coordinate the change with the pipeline to avoid updating the document title before the navigation is committed, but that shouldn't be a problem.

Paired with #74, the new signature of `activate` and `canActivate` could be

```javascript
activate(params, routeConfig, navModel)
```

Or we could even collapse both config and navModel into a `route` object if we want to bundle everything up together.

Thoughts?

**Comment by bryanrsmith** [comment]
On second thought, perhaps `canActivate` should not receive the navModel at all. We should probably wait until we've decided to activate before making changes like setting the title.

**Comment by EisenbergEffect** [comment]
Correct, we don't want anyone changing the title until the activate phase. One trick to bear in mind is that the title property is designed to be databound to and if we make it into a getter/setter then we can't bind to it without dirty checking it, so we need to avoid that somehow... If we can keep the title a simple property, that would be best. We might need some additional api that could update the title property and cause a rengeration of the document's title, which you mention.

Any ideas how long it would take to get this working?

**Comment by bryanrsmith** [comment]
Right, I forgot about the data binding. Maybe a title property for binding and a setTitle method that sets it & then handles the document.title change?

I wouldn't expect it to take more than an hour or two. I might be able to make the API change quickly if I can't find the time for the full fix tonight.

**Comment by EisenbergEffect** [comment]
Yes, I think that would be the way to go. We can do the release on Tuesday if you want some extra time to get this in. I can easily s

**Comment by bryanrsmith** [comment]
I looked closer at this last night. Splitting navModel from config will take a bit more work than I originally estimated. The config object is what gets passed around as the main route representation, including in the route recognizer, so I think we'd need to change the internal representation of a route to make navModel a sibling of the config. I don't think I can confidently get that done by tomorrow. A few options...

1. We can stick with the plan, but bump the change to next release.
2. I can hack in the API change so that we start adding navModel as the third parameter to `activate` and `canActivate`. I'd circle back and fill in the internal refactor and fix the main issue of delayed title setting before the next release.
3. We can leave navModel on the config object so that we don't need the more extensive refactor. I discovered that we actually *don't* allow the consumer to provide their own navModel object, so this wouldn't be as bad as I originally suggested it might be. We could safely replace the plain navModel object with a class instance. This would be less work, and the change could probably be non-breaking. We'd just start recommending the use of `config.navModel.setTitle(newTitle)` instead of `config.navModel.title = newTitle`.

Option 3 is looking more attractive to me now that I know navModel isn't part of the initial config object provided by the consumer. I'd like it even better if the documentation and sample apps renamed the `activate` parameter name from "config" to "route", or something to better indicate that it's a stateful object.

```
activate(params, route, navigationInstruction) { // I neglected to include the final navigationInstruction parameter in earlier posts
  route.navModel.setTitle('New Title');
}
```

**Comment by EisenbergEffect** [comment]
Ok, I think I agree with you. Let's go with 3 and we can work on renaming things in code and docs to support the idea. How does that sound? Thoughts on when this might be ready? No rush. I'd like to know if I should wait on the release or go ahead and do it tomorrow.
